<?php

include_once "../config/DataBase.php";

// $db = new DataBase;

class Services {
    private $clientId = '3a7f9l8f0153pkje5tl423a2bq'; 
    private $clientSecret = '5pqfvla73k584p7ioc1im1cddt0grpu350gucrksnuub4cm3goo';
    private $apiKey = 'ZIdttfc2Dc5iT4i7BT1pm35FNwJPvenI9ytiUsnm';
    private $authUri = null;
    private $authGrantType = null;
    private $apiBasePath = null;

    public function __construct() {
        
    }

    public function login(){

    }

    public function logout(){

    }

    public function almacenarLogs($comando, $usuario){
        $table = "log_commands";
        $columns = "comando_id, usuario_id";
        $values = "$comando, $usuario";

        $r = $db->insertOnTable($table, $columns, $values);
        if ($r->error == 0) {
            # code...
        }else{

        }
    }

    public function sendArmCommand($device_id, $user_id, $command){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://flespi.io/gw/devices/$device_id/settings/arm");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');

        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"properties\":{\"arm\":$command},\"address\":\"connection\"}");

        $headers = array();
        $headers[] = 'Accept: application/json';
        $headers[] = 'Authorization: FlespiToken BeKr3C9Eb8bkKKzvItfM74OMepYoh83JaBY11Vv2Tvcs3zLCTRcOJOqN3cZb8TI6';
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            return json_encode(["error" => 1, "data" => 'Error:' . curl_error($ch)]);
        }else{
            $this->almacenarLogs($comando, $user_id);
            return json_encode(["error" => 0, "data" => $result]);
        }
        curl_close($ch);
    }

}